=== j0mba/GDI/Atividade extra/Paciente/paciente.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="CLINICA">
		<xs:element name="PACIENTE">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="CPF">
						<xs:simpleType>
							<xs:restriction base="xs:integer">
								<xs:length value="11"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
			        <xs:element name="NOME" type="xs:string"/>
			        <xs:element name="SEXO">
						<xs:simpleType>
						    <xs:restriction base="xs:string">
						    	<xs:pattern value="M|F"/>
						    </xs:restriction>
						</xs:simpleType>
					</xs:element>
			        <xs:element name="DATA_NASCIMENTO" type="xs:date"/>
			        <xs:element name="PLANO_DE_SAUDE" type="xs:string"/>
			        <xs:element name="TELEFONES">
			        	<xs:all>
			        		<xs:element name="TP_FONE">
			        			<xs:element name="NUMERO" type="xs:integer"/>
			        		</xs:element>
			        	</xs:all>
			        </xs:element>
			        <xs:element name="ENDERECO">
						<xs:sequence>
				            <xs:element name="CEP" type="xs:integer"/>
				            <xs:element name="LOGRADOURO" type="xs:string"/>
				            <xs:element name="NUMERO" type="xs:integer"/>
				            <xs:element name="BAIRRO" type="xs:string"/>
				            <xs:element name="CIDADE" type="xs:string"/>
							<xs:element name="ESTADO">
								<xs:simpleType>
								    <xs:restriction base="xs:string">
								      	<xs:enumeration value="AC"/>
								      	<xs:enumeration value="AL"/>
								      	<xs:enumeration value="AP"/>
								      	<xs:enumeration value="AM"/>
								      	<xs:enumeration value="BA"/>
								      	<xs:enumeration value="CE"/>
								      	<xs:enumeration value="DF"/>
								      	<xs:enumeration value="ES"/>
								      	<xs:enumeration value="GO"/>
								      	<xs:enumeration value="MA"/>
								      	<xs:enumeration value="MT"/>
								      	<xs:enumeration value="MS"/>
								      	<xs:enumeration value="MG"/>
								      	<xs:enumeration value="PA"/>
								      	<xs:enumeration value="PB"/>
								      	<xs:enumeration value="PR"/>
								      	<xs:enumeration value="PE"/>
								      	<xs:enumeration value="PI"/>
								      	<xs:enumeration value="RJ"/>
								      	<xs:enumeration value="RN"/>
								      	<xs:enumeration value="RS"/>
								      	<xs:enumeration value="RO"/>
								      	<xs:enumeration value="RR"/>
								      	<xs:enumeration value="SC"/>
								      	<xs:enumeration value="SP"/>
								      	<xs:enumeration value="SE"/>
								      	<xs:enumeration value="TO"/>
								    </xs:restriction>
								</xs:simpleType>
							</xs:element> 
						</xs:sequence>
			        </xs:element>
			        <xs:element name="PRODUTO">
						<xs:sequence>
				            <xs:element name="ID" type="xs:integer"/>
				            <xs:element name="NOME" type="xs:string"/>
				            <xs:element name="PRECO" type="xs:decimal"/>
				            <xs:element name="DOSE" type="xs:string"/>
				            <xs:element name="VALIDADE" type="xs:date"/>
						</xs:sequence>
			        </xs:element>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	</xs:element>
</xs:schema>

=== j0mba/GDI/Atividade extra/Paciente/paciente.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="paciente.css"?>
    <CLINICA xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com paciente.xsd">
        <PACIENTE>
            <CPF>56071103541</CPF>


            <NOME_COMPLETO>Rana W. Garcia</NOME_COMPLETO>
            <SEXO>F</SEXO>


            <DATA_NASCIMENTO>04-MAR-73</DATA_NASCIMENTO>


            <PLANO_DE_SAUDE>Hapvida</PLANO_DE_SAUDE>
            <TELEFONES>
                <TP_FONE>


                    <NUMERO>11986718597</NUMERO>
                </TP_FONE>
            </TELEFONES>
            <ENDERECO>


                <CEP>25698381</CEP>
                <LOGRADOURO>Vel Avenue</LOGRADOURO>


                <NUMERO>7833</NUMERO>
                <BAIRRO>Diamantina</BAIRRO>
                <CIDADE>Ribeirão Preto
                </CIDADE>
                <ESTADO>SP</ESTADO>
            </ENDERECO>
            <PRODUTO>
                <ID>8</ID>


                <NOME>Dipirona</NOME>
                <PRECO>14.99</PRECO>
                <DOSE>500mg</DOSE>


                <VALIDADE>28-OCT-22</VALIDADE>
            </PRODUTO>
        </PACIENTE>
        <PACIENTE>


            <CPF>56071103541</CPF>
            <NOME_COMPLETO>Rana W. Garcia</NOME_COMPLETO>


            <SEXO>F</SEXO>
            <DATA_NASCIMENTO>04-MAR-73</DATA_NASCIMENTO>


            <PLANO_DE_SAUDE>Hapvida</PLANO_DE_SAUDE>
            <TELEFONES>
                <TP_FONE>


                    <NUMERO>11986718597</NUMERO>
                </TP_FONE>
            </TELEFONES>
            <ENDERECO>


                <CEP>25698381</CEP>
                <LOGRADOURO>Vel Avenue</LOGRADOURO>


                <NUMERO>7833</NUMERO>
                <BAIRRO>Diamantina</BAIRRO>
                <CIDADE>Ribeirão Preto
                </CIDADE>
                <ESTADO>SP</ESTADO>
            </ENDERECO>
            <PRODUTO>
                <ID>1</ID>


                <NOME>Levofloxacina</NOME>
                <PRECO>99.99</PRECO>
                <DOSE>250mg</DOSE>


                <VALIDADE>27-AUG-22</VALIDADE>
            </PRODUTO>
        </PACIENTE>
        <PACIENTE>


            <CPF>12130599361</CPF>
            <NOME_COMPLETO>Cade Q. Alston</NOME_COMPLETO>


            <SEXO>M</SEXO>
            <DATA_NASCIMENTO>17-NOV-12</DATA_NASCIMENTO>


            <PLANO_DE_SAUDE>Hapvida</PLANO_DE_SAUDE>
            <TELEFONES>
                <TP_FONE>


                    <NUMERO>11981338155</NUMERO>
                </TP_FONE>
            </TELEFONES>
            <ENDERECO>


                <CEP>58051550</CEP>
                <LOGRADOURO>Scelerisque St.</LOGRADOURO>


                <NUMERO>2328</NUMERO>
                <BAIRRO>Suvaco da Ovelha</BAIRRO>
                <CIDADE>Ribeirão Preto
                </CIDADE>
                <ESTADO>SP</ESTADO>
            </ENDERECO>
            <PRODUTO>
                <ID>7</ID>


                <NOME>Ibuprofeno</NOME>
                <PRECO>24.99</PRECO>
                <DOSE>100mg/ml</DOSE>


                <VALIDADE>22-NOV-22</VALIDADE>
            </PRODUTO>
        </PACIENTE>
        <PACIENTE>


            <CPF>12130599361</CPF>
            <NOME_COMPLETO>Cade Q. Alston</NOME_COMPLETO>


            <SEXO>M</SEXO>
            <DATA_NASCIMENTO>17-NOV-12</DATA_NASCIMENTO>


            <PLANO_DE_SAUDE>Hapvida</PLANO_DE_SAUDE>
            <TELEFONES>
                <TP_FONE>


                    <NUMERO>11981338155</NUMERO>
                </TP_FONE>
            </TELEFONES>
            <ENDERECO>


                <CEP>58051550</CEP>
                <LOGRADOURO>Scelerisque St.</LOGRADOURO>


                <NUMERO>2328</NUMERO>
                <BAIRRO>Suvaco da Ovelha</BAIRRO>
                <CIDADE>Ribeirão Preto
                </CIDADE>
                <ESTADO>SP</ESTADO>
            </ENDERECO>
            <PRODUTO>
                <ID>3</ID>


                <NOME>Ciprofloxacina</NOME>
                <PRECO>69.99</PRECO>
                <DOSE>250mg</DOSE>


                <VALIDADE>12-APR-18</VALIDADE>
            </PRODUTO>
        </PACIENTE>
        <PACIENTE>


            <CPF>68804766912</CPF>
            <NOME_COMPLETO>Daquan H. Dillon</NOME_COMPLETO>


            <SEXO>M</SEXO>
            <DATA_NASCIMENTO>06-JAN-13</DATA_NASCIMENTO>


            <PLANO_DE_SAUDE>Hapvida</PLANO_DE_SAUDE>
            <TELEFONES>
                <TP_FONE>


                    <NUMERO>11998446495</NUMERO>
                </TP_FONE>
            </TELEFONES>
            <ENDERECO>


                <CEP>88700443</CEP>
                <LOGRADOURO>Lorem Rd.</LOGRADOURO>


                <NUMERO>1385</NUMERO>
                <BAIRRO>Suvaco da Ovelha</BAIRRO>
                <CIDADE>Ribeirão Preto
                </CIDADE>
                <ESTADO>SP</ESTADO>
            </ENDERECO>
            <PRODUTO>
                <ID>19</ID>


                <NOME>Urocultura</NOME>
                <PRECO>199.99</PRECO>
            </PRODUTO>
        </PACIENTE>


        <PACIENTE>
            <CPF>68804766912</CPF>
            <NOME_COMPLETO>Daquan H. Dillon
            </NOME_COMPLETO>
            <SEXO>M</SEXO>


            <DATA_NASCIMENTO>06-JAN-13</DATA_NASCIMENTO>


            <PLANO_DE_SAUDE>Hapvida</PLANO_DE_SAUDE>
            <TELEFONES>
                <TP_FONE>


                    <NUMERO>11998446495</NUMERO>
                </TP_FONE>
            </TELEFONES>
            <ENDERECO>


                <CEP>88700443</CEP>
                <LOGRADOURO>Lorem Rd.</LOGRADOURO>


                <NUMERO>1385</NUMERO>
                <BAIRRO>Suvaco da Ovelha</BAIRRO>
                <CIDADE>Ribeirão Preto
                </CIDADE>
                <ESTADO>SP</ESTADO>
            </ENDERECO>
            <PRODUTO>
                <ID>4</ID>


                <NOME>Cefepima</NOME>
                <PRECO>39.99</PRECO>
                <DOSE>1g</DOSE>


                <VALIDADE>16-FEB-17</VALIDADE>
            </PRODUTO>
        </PACIENTE>
        <PACIENTE>


            <CPF>76764741465</CPF>
            <NOME_COMPLETO>Lewis Q. Swanson</NOME_COMPLETO>


            <SEXO>M</SEXO>
            <DATA_NASCIMENTO>26-JUN-59</DATA_NASCIMENTO>


            <PLANO_DE_SAUDE>Hapvida</PLANO_DE_SAUDE>
            <TELEFONES>
                <TP_FONE>


                    <NUMERO>11981106371</NUMERO>
                </TP_FONE>
            </TELEFONES>
            <ENDERECO>


                <CEP>44980216</CEP>
                <LOGRADOURO>Arcu Av.</LOGRADOURO>


                <NUMERO>2900</NUMERO>
                <BAIRRO>Diamantina</BAIRRO>
                <CIDADE>Ribeirão Preto
                </CIDADE>
                <ESTADO>SP</ESTADO>
            </ENDERECO>
            <PRODUTO>
                <ID>5</ID>


                <NOME>Penicilina Benzatina</NOME>
                <PRECO>5.99</PRECO>
                <DOSE>250mi Und.
                </DOSE>
                <VALIDADE>20-JAN-16</VALIDADE>
            </PRODUTO>
        </PACIENTE>


        <PACIENTE>
            <CPF>76764741465</CPF>
            <NOME_COMPLETO>Lewis Q. Swanson
            </NOME_COMPLETO>
            <SEXO>M</SEXO>


            <DATA_NASCIMENTO>26-JUN-59</DATA_NASCIMENTO>


            <PLANO_DE_SAUDE>Hapvida</PLANO_DE_SAUDE>
            <TELEFONES>
                <TP_FONE>


                    <NUMERO>11981106371</NUMERO>
                </TP_FONE>
            </TELEFONES>
            <ENDERECO>


                <CEP>44980216</CEP>
                <LOGRADOURO>Arcu Av.</LOGRADOURO>


                <NUMERO>2900</NUMERO>
                <BAIRRO>Diamantina</BAIRRO>
                <CIDADE>Ribeirão Preto
                </CIDADE>
                <ESTADO>SP</ESTADO>
            </ENDERECO>
            <PRODUTO>
                <ID>15</ID>


                <NOME>Sorologia VDRL</NOME>
                <PRECO>109.99</PRECO>
            </PRODUTO>
        </PACIENTE>


        <PACIENTE>
            <CPF>76764741465</CPF>
            <NOME_COMPLETO>Lewis Q. Swanson
            </NOME_COMPLETO>
            <SEXO>M</SEXO>


            <DATA_NASCIMENTO>26-JUN-59</DATA_NASCIMENTO>


            <PLANO_DE_SAUDE>Hapvida</PLANO_DE_SAUDE>
            <TELEFONES>
                <TP_FONE>


                    <NUMERO>11981106371</NUMERO>
                </TP_FONE>
            </TELEFONES>
            <ENDERECO>


                <CEP>44980216</CEP>
                <LOGRADOURO>Arcu Av.</LOGRADOURO>


                <NUMERO>2900</NUMERO>
                <BAIRRO>Diamantina</BAIRRO>
                <CIDADE>Ribeirão Preto
                </CIDADE>
                <ESTADO>SP</ESTADO>
            </ENDERECO>
            <PRODUTO>
                <ID>16</ID>


                <NOME>Sorologia FTA-ABS</NOME>
                <PRECO>79.99</PRECO>
            </PRODUTO>


        </PACIENTE>
        <PACIENTE>
            <CPF>76764741465</CPF>
            <NOME_COMPLETO>Lewis Q. Swanson
            </NOME_COMPLETO>
            <SEXO>M</SEXO>


            <DATA_NASCIMENTO>26-JUN-59</DATA_NASCIMENTO>


            <PLANO_DE_SAUDE>Hapvida</PLANO_DE_SAUDE>
            <TELEFONES>
                <TP_FONE>


                    <NUMERO>11981106371</NUMERO>
                </TP_FONE>
            </TELEFONES>
            <ENDERECO>


                <CEP>44980216</CEP>
                <LOGRADOURO>Arcu Av.</LOGRADOURO>


                <NUMERO>2900</NUMERO>
                <BAIRRO>Diamantina</BAIRRO>
                <CIDADE>Ribeirão Preto
                </CIDADE>
                <ESTADO>SP</ESTADO>
            </ENDERECO>
            <PRODUTO>
                <ID>17</ID>


                <NOME>Hemograma</NOME>
                <PRECO>10.99</PRECO>
            </PRODUTO>
        </PACIENTE>


        <PACIENTE>
            <CPF>76764741465</CPF>
            <NOME_COMPLETO>Lewis Q. Swanson
