=== j0mba/GDI/Atividade extra/Laboratorio/laboratorio.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CLINICA">
    <xs:element name="LABORATORIO">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="ID">
            <xs:simpleType>
              <xs:restriction base="xs:integer">
                <xs:length value="3"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
          <xs:element name="NOME" type="xs:string"/>
          <xs:element name="LABORATORIO_TELEFONE">
            <xs:all>
              <xs:element name="TP_FONE">
                <xs:element name="NUMERO" type="xs:integer"/>
              </xs:element>
            </xs:all>
          </xs:element>
          <xs:element name="LABORATORIO_ENDERECO">
            <xs:sequence>
              <xs:element name="CEP" type="xs:integer"/>
              <xs:element name="LOGRADOURO" type="xs:string"/>
              <xs:element name="NUMERO" type="xs:integer"/>
              <xs:element name="BAIRRO" type="xs:string"/>
              <xs:element name="CIDADE" type="xs:string"/>
              <xs:element name="ESTADO">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="AC"/>
                        <xs:enumeration value="AL"/>
                        <xs:enumeration value="AP"/>
                        <xs:enumeration value="AM"/>
                        <xs:enumeration value="BA"/>
                        <xs:enumeration value="CE"/>
                        <xs:enumeration value="DF"/>
                        <xs:enumeration value="ES"/>
                        <xs:enumeration value="GO"/>
                        <xs:enumeration value="MA"/>
                        <xs:enumeration value="MT"/>
                        <xs:enumeration value="MS"/>
                        <xs:enumeration value="MG"/>
                        <xs:enumeration value="PA"/>
                        <xs:enumeration value="PB"/>
                        <xs:enumeration value="PR"/>
                        <xs:enumeration value="PE"/>
                        <xs:enumeration value="PI"/>
                        <xs:enumeration value="RJ"/>
                        <xs:enumeration value="RN"/>
                        <xs:enumeration value="RS"/>
                        <xs:enumeration value="RO"/>
                        <xs:enumeration value="RR"/>
                        <xs:enumeration value="SC"/>
                        <xs:enumeration value="SP"/>
                        <xs:enumeration value="SE"/>
                        <xs:enumeration value="TO"/>
                    </xs:restriction>
                </xs:simpleType>
              </xs:element> 
            </xs:sequence>
          </xs:element>
        </xs:sequence>
      </xs:complexType>
    </xs:element>
  </xs:element>
</xs:schema>

=== j0mba/GDI/Atividade extra/Laboratorio/laboratorio.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="laboratorio.css"?>
<CLINICA xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com laboratorio.xsd">
 <LABORATORIO>
  <CODIGO>1</CODIGO>

<LABORATORIO_NOME>Laboratório Freeman</LABORATORIO_NOME>

<LABORATORIO_ENDERECO>
   <CEP>14085020</CEP>
   <LOGRADOURO>Floriano
Peixoto</LOGRADOURO>
   <NUMERO>537</NUMERO>
   <BAIRRO>Vila dos
Jacarandás</BAIRRO>
   <CIDADE>Olinda</CIDADE>
   <ESTADO>PE</ESTADO>

</LABORATORIO_ENDERECO>
  <LABORATORIO_TELEFONE>
   <TP_FONE>

<NUMERO>8121564478</NUMERO>
   </TP_FONE>
   <TP_FONE>

<NUMERO>8121564479</NUMERO>
   </TP_FONE>
  </LABORATORIO_TELEFONE>

</LABORATORIO>
 <LABORATORIO>
  <CODIGO>2</CODIGO>

<LABORATORIO_NOME>Laboratório Flowers</LABORATORIO_NOME>

<LABORATORIO_ENDERECO>
   <CEP>14085540</CEP>
   <LOGRADOURO>Marechal
Deodoro</LOGRADOURO>
   <NUMERO>145</NUMERO>
   <BAIRRO>Vila dos
Jabuticabais</BAIRRO>
   <CIDADE>Olinda</CIDADE>
   <ESTADO>PE</ESTADO>

</LABORATORIO_ENDERECO>
  <LABORATORIO_TELEFONE>
   <TP_FONE>

<NUMERO>8121324553</NUMERO>
   </TP_FONE>
   <TP_FONE>

<NUMERO>8121546698</NUMERO>
   </TP_FONE>
  </LABORATORIO_TELEFONE>

</LABORATORIO>
 <LABORATORIO>
  <CODIGO>3</CODIGO>

<LABORATORIO_NOME>Laboratório Greene</LABORATORIO_NOME>

<LABORATORIO_ENDERECO>
   <CEP>14085470</CEP>
   <LOGRADOURO>Conde de
Assumar</LOGRADOURO>
   <NUMERO>98</NUMERO>
   <BAIRRO>Jardim das
Laranjeiras</BAIRRO>
   <CIDADE>Recife</CIDADE>
   <ESTADO>PE</ESTADO>

</LABORATORIO_ENDERECO>
  <LABORATORIO_TELEFONE>
   <TP_FONE>

<NUMERO>8121770400</NUMERO>
   </TP_FONE>
  </LABORATORIO_TELEFONE>

</LABORATORIO>
 <LABORATORIO>
  <CODIGO>4</CODIGO>

<LABORATORIO_NOME>Laboratório Soto</LABORATORIO_NOME>
  <LABORATORIO_ENDERECO>

<CEP>14085180</CEP>
   <LOGRADOURO>Rua da Palmeira</LOGRADOURO>

<NUMERO>133</NUMERO>
   <BAIRRO>Vale do Beberibe</BAIRRO>

<CIDADE>Recife</CIDADE>
   <ESTADO>PE</ESTADO>
  </LABORATORIO_ENDERECO>

<LABORATORIO_TELEFONE>
   <TP_FONE>
    <NUMERO>8121234674</NUMERO>

</TP_FONE>
   <TP_FONE>
    <NUMERO>8121567256</NUMERO>
   </TP_FONE>

<TP_FONE>
    <NUMERO>8121225777</NUMERO>
   </TP_FONE>

</LABORATORIO_TELEFONE>
 </LABORATORIO>
 <LABORATORIO>
  <CODIGO>5</CODIGO>

<LABORATORIO_NOME>Laboratório Bolton</LABORATORIO_NOME>

<LABORATORIO_ENDERECO>
   <CEP>14085660</CEP>
   <LOGRADOURO>Rua das
Mangas</LOGRADOURO>
   <NUMERO>32</NUMERO>
   <BAIRRO>Vale do
Capibaribe</BAIRRO>
   <CIDADE>Recife</CIDADE>
   <ESTADO>PE</ESTADO>

</LABORATORIO_ENDERECO>
  <LABORATORIO_TELEFONE>
   <TP_FONE>

<NUMERO>8121668436</NUMERO>
   </TP_FONE>
  </LABORATORIO_TELEFONE>

</LABORATORIO>
 <LABORATORIO>
  <CODIGO>6</CODIGO>

<LABORATORIO_NOME>Laboratório Moore</LABORATORIO_NOME>
  <LABORATORIO_ENDERECO>

<CEP>14085890</CEP>
   <LOGRADOURO>Rua do Açúcar</LOGRADOURO>

<NUMERO>58</NUMERO>
   <BAIRRO>Várzea Grande</BAIRRO>

<CIDADE>Recife</CIDADE>
   <ESTADO>PE</ESTADO>
  </LABORATORIO_ENDERECO>

<LABORATORIO_TELEFONE>
   <TP_FONE>
    <NUMERO>8121255685</NUMERO>

</TP_FONE>
  </LABORATORIO_TELEFONE>
 </LABORATORIO>
 <LABORATORIO>

<CODIGO>7</CODIGO>
  <LABORATORIO_NOME>Laboratório Hernandez</LABORATORIO_NOME>

<LABORATORIO_ENDERECO>
   <CEP>14085034</CEP>
   <LOGRADOURO>Princesa
Isabel</LOGRADOURO>
   <NUMERO>29</NUMERO>
   <BAIRRO>Vila dos
Mamoeiros</BAIRRO>
   <CIDADE>Olinda</CIDADE>
   <ESTADO>PE</ESTADO>

</LABORATORIO_ENDERECO>
  <LABORATORIO_TELEFONE>
   <TP_FONE>

<NUMERO>8121864773</NUMERO>
   </TP_FONE>
   <TP_FONE>

<NUMERO>8121217008</NUMERO>
   </TP_FONE>
  </LABORATORIO_TELEFONE>

</LABORATORIO>
 <LABORATORIO>
  <CODIGO>8</CODIGO>

<LABORATORIO_NOME>Laboratório Knowles</LABORATORIO_NOME>

<LABORATORIO_ENDERECO>
   <CEP>14085045</CEP>
   <LOGRADOURO>Joaquim
Nabuco</LOGRADOURO>
   <NUMERO>72</NUMERO>
   <BAIRRO>Mártir da Cruz</BAIRRO>

<CIDADE>Recife</CIDADE>
   <ESTADO>PE</ESTADO>
  </LABORATORIO_ENDERECO>

<LABORATORIO_TELEFONE>
   <TP_FONE>
    <NUMERO>8121356709</NUMERO>

</TP_FONE>
   <TP_FONE>
    <NUMERO>8121435785</NUMERO>
   </TP_FONE>

<TP_FONE>
    <NUMERO>8121563289</NUMERO>
   </TP_FONE>
   <TP_FONE>

<NUMERO>8121468903</NUMERO>
   </TP_FONE>
  </LABORATORIO_TELEFONE>

</LABORATORIO>
 <LABORATORIO>
  <CODIGO>9</CODIGO>

<LABORATORIO_NOME>Laboratório Calhoun</LABORATORIO_NOME>

<LABORATORIO_ENDERECO>
   <CEP>14085666</CEP>
   <LOGRADOURO>Castro
Alves</LOGRADOURO>
   <NUMERO>54</NUMERO>
   <BAIRRO>Conciliação</BAIRRO>

<CIDADE>Recife</CIDADE>
   <ESTADO>PE</ESTADO>
  </LABORATORIO_ENDERECO>

<LABORATORIO_TELEFONE>
   <TP_FONE>
    <NUMERO>8121113528</NUMERO>

</TP_FONE>
   <TP_FONE>
    <NUMERO>8121743399</NUMERO>
   </TP_FONE>

</LABORATORIO_TELEFONE>
 </LABORATORIO>
 <LABORATORIO>
  <CODIGO>10</CODIGO>

<LABORATORIO_NOME>Laboratório Ramsey</LABORATORIO_NOME>

<LABORATORIO_ENDERECO>
   <CEP>14085875</CEP>
   <LOGRADOURO>Dom Pedro
II</LOGRADOURO>
   <NUMERO>26</NUMERO>
   <BAIRRO>Mártir da Cruz</BAIRRO>

<CIDADE>Recife</CIDADE>
   <ESTADO>PE</ESTADO>
  </LABORATORIO_ENDERECO>

<LABORATORIO_TELEFONE>
   <TP_FONE>
    <NUMERO>8121224290</NUMERO>

</TP_FONE>
   <TP_FONE>
    <NUMERO>8121244270</NUMERO>
   </TP_FONE>

<TP_FONE>
    <NUMERO>8121347801</NUMERO>
   </TP_FONE>

</LABORATORIO_TELEFONE>
 </LABORATORIO>
 <LABORATORIO>
  <CODIGO>11</CODIGO>

<LABORATORIO_NOME>Laboratório Richardson</LABORATORIO_NOME>

<LABORATORIO_ENDERECO>
   <CEP>14085082</CEP>
   <LOGRADOURO>Rua das
Rosas</LOGRADOURO>
   <NUMERO>451</NUMERO>
   <BAIRRO>Jardim Verde</BAIRRO>

<CIDADE>Olinda</CIDADE>
   <ESTADO>PE</ESTADO>
  </LABORATORIO_ENDERECO>

<LABORATORIO_TELEFONE>
   <TP_FONE>
    <NUMERO>8121335689</NUMERO>

</TP_FONE>
   <TP_FONE>
    <NUMERO>8121246982</NUMERO>
   </TP_FONE>

</LABORATORIO_TELEFONE>
 </LABORATORIO>
 <LABORATORIO>
  <CODIGO>12</CODIGO>

<LABORATORIO_NOME>Laboratório Stafford</LABORATORIO_NOME>

<LABORATORIO_ENDERECO>
   <CEP>14085017</CEP>
   <LOGRADOURO>Rua das
Sete</LOGRADOURO>
   <NUMERO>30</NUMERO>
   <BAIRRO>Porto Largo</BAIRRO>

<CIDADE>Recife</CIDADE>
   <ESTADO>PE</ESTADO>
  </LABORATORIO_ENDERECO>

<LABORATORIO_TELEFONE>
   <TP_FONE>
    <NUMERO>8121234765</NUMERO>

</TP_FONE>
  </LABORATORIO_TELEFONE>
 </LABORATORIO>
 <LABORATORIO>

<CODIGO>13</CODIGO>
  <LABORATORIO_NOME>Laboratório Rosa</LABORATORIO_NOME>

<LABORATORIO_ENDERECO>
   <CEP>14085342</CEP>
   <LOGRADOURO>Rua do
Cascalho</LOGRADOURO>
   <NUMERO>451</NUMERO>
   <BAIRRO>Largo do
Rosário</BAIRRO>
   <CIDADE>Recife</CIDADE>
   <ESTADO>PE</ESTADO>

</LABORATORIO_ENDERECO>
  <LABORATORIO_TELEFONE>
   <TP_FONE>

<NUMERO>8121557230</NUMERO>
   </TP_FONE>
  </LABORATORIO_TELEFONE>

</LABORATORIO>
 <LABORATORIO>
  <CODIGO>14</CODIGO>

<LABORATORIO_NOME>Laboratório Meyers</LABORATORIO_NOME>

<LABORATORIO_ENDERECO>
   <CEP>14085165</CEP>
   <LOGRADOURO>Rua do
Mel</LOGRADOURO>
   <NUMERO>44</NUMERO>
   <BAIRRO>Jardim das
Carambolas</BAIRRO>
   <CIDADE>Olinda</CIDADE>
   <ESTADO>PE</ESTADO>

</LABORATORIO_ENDERECO>
  <LABORATORIO_TELEFONE>
   <TP_FONE>

<NUMERO>8121156789</NUMERO>
   </TP_FONE>
  </LABORATORIO_TELEFONE>

</LABORATORIO>
 <LABORATORIO>
  <CODIGO>15</CODIGO>

<LABORATORIO_NOME>Laboratório Odom</LABORATORIO_NOME>
  <LABORATORIO_ENDERECO>

<CEP>14085731</CEP>
   <LOGRADOURO>Rua das Janelas</LOGRADOURO>

<NUMERO>62</NUMERO>
   <BAIRRO>Fundição</BAIRRO>
   <CIDADE>Recife</CIDADE>

<ESTADO>PE</ESTADO>
  </LABORATORIO_ENDERECO>
  <LABORATORIO_TELEFONE>

<TP_FONE>
    <NUMERO>8121233861</NUMERO>
   </TP_FONE>
   <TP_FONE>

<NUMERO>8121444770</NUMERO>
   </TP_FONE>
  </LABORATORIO_TELEFONE>

</LABORATORIO>
</CLINICA>
